### ISSUE TITLE
The cat got lost 

### ISSUE THREAD

**Issue by MetaSeb** [d4rk-d4nph3/Ransim#1]
Hello,

The cat.jpg file used by the ransim.exe program is no longer available (error 404) :

 https://github.com/d4rk-d4nph3/test/raw/master/cat.jpg

Can I find it elsewhere?

**Comment by corsch** [comment]
This would be a huge help, as cat.jpg is the required crypt0.dll

**Comment by corsch** [comment]
I've just changed the URL to my own server and used a generic file, as the cat.jpg is nor used in the code after downloading.

**Comment by d4rk-d4nph3** [comment]
Just change this URL in this line to any image in the internet.
https://github.com/d4rk-d4nph3/Ransim/blob/master/Ransim/Program.cs#L90

**Comment by corsch** [comment]
It should be a (dummy) DLL, or you will get an error message while running the tool.

I've compiled and used PopCalc  (https://github.com/CuckooEXE/PopCalc)

**Comment by d4rk-d4nph3** [comment]
You are right. I got confused. I am thinking of adding new features and I might take this issue into consideration.

**Comment by corsch** [comment]
Thank you very much!

**Comment by d4rk-d4nph3** [comment]
New features being added in [v0.2](/d4rk-d4nph3/Ransim/tree/v0.2) branch.

**Comment by corsch** [comment]
Thank you for your great work and developing a new version :)

**Comment by d4rk-d4nph3** [comment]
It's my pleasure. The roadmap is to release v0.2 by the end of this month.

**Comment by d4rk-d4nph3** [comment]
@MetaSeb @corsch, v0.2 beta (https://github.com/d4rk-d4nph3/Ransim/pull/2) has been merged to master!

Let me know what you get of this.
